#macro ROOM_START rLevel01
#macro WIDTH 320
#macro HEIGHT 180
#macro SURFACE_WIDTH (WIDTH)
#macro SURFACE_HEIGHT (HEIGHT)
#macro DISPLAY_WIDTH (WIDTH)
#macro DISPLAY_HEIGHT (HEIGHT)
#macro SAVE_DATA global.saveData
#macro PUBSUB_MANAGER global.pubsubManager
